# Generated by Django 3.1.5 on 2021-01-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('person_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planet')),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
