# Generated by Django 3.1.5 on 2021-01-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='homeworld',
        ),
    ]
