# Generated by Django 3.1.5 on 2021-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('planet_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('diameter', models.IntegerField()),
                ('rotation_period', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('gravity', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('climate', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
                ('surface_water', models.IntegerField()),
            ],
            options={
                'db_table': 'planets',
            },
        ),
    ]
